### ISSUE TITLE
Remove request to database from init method

### ISSUE THREAD

**Issue by petedejoy** [astronomer/airflow-provider-great-expectations#18]
The [GreatExpecatationsBigQueryOperator](https://github.com/great-expectations/airflow-provider-great-expectations/blob/main/great_expectations_provider/operators/great_expectations_bigquery.py) makes a `get_connection` request in the `init` method of the class. This is problematic for a few reasons:
- It causes a fatal DAG import error if the connection string is not defined.
- It will consume unnecessary scheduler resources. Every time the Airflow scheduler parses a DAG, Airflow will execute whatever is contained in the `init` method of your class. If the `init` method makes requests to the database or over the network, it will place an unnecessary burden on the database.

The general pattern to follow is to have `init` store the `conn_id` string and build the hook via `get_connection` at runtime.

**Comment by Milchdealer** [comment]
Additionally, please change
```
credentials_path = connection_json['extra__google_cloud_platform__key_path']
```

to a `.get()` call because if you use GKE + workload identities, then the google credentials are baked in via the metadata API. I just have a dummy definition of my default connection with (almost) no values, that during the runtime is replaced by the `google.auth.default()` call.

**Comment by jeffkpayne** [comment]
There are also other limitations related to how the `data_context` attribute is initialized inside `__init__()`.  For instance, the `gcp_project` parameter can't be templated because it's passed into the `DataContextConfig` created in `__init__()`.  Moving the `data_context` initialization logic into `execute()` would allow the other attributes to be templated, in addition to addressing the primary concerns of this issue.

**Comment by jeffkpayne** [comment]
@petedejoy Were you planning on opening a PR to address this?

**Comment by petedejoy** [comment]
@jeffkpayne I don't have any branch in progress- we welcome community PRs if you're interested in getting involved :)

**Comment by jeffkpayne** [comment]
FYI, I'm working on this actively (for work) and will be opening a PR, hopefully some time next week. Just need to get setup locally per the standards of this repo.
